#!/usr/bin/env bash

sudo add-apt-repository -y ppa:longsleep/golang-backports

sudo apt -y update
sudo apt -y install \
  git \
  jq \
  stow \
  curl \
  ffmpeg \
  fzf \
  tree \
  htop \
  fd-find \
  ripgrep \
  bat \
  golang-go \
  sqlite3 \
  tmux \
  xclip

export PATH="$HOME/.local/bin:$PATH"
mkdir -p $HOME/.local/bin/fd
ln -s $(which fdfind) $HOME/.local/bin/fd
