#!/usr/bin/env bash

sudo apt -y update
sudo apt -y install \
  git \
  jq \
  stow \
  curl \
  ffmpeg \
  fzf \
  tree \
  htop \
  fd-find \
  ripgrep \
  bat \
  nvim

export PATH="$HOME/.local/bin:$PATH"
mkdir -p $HOME/.local/bin/fd
ln -s $(which fdfind) $HOME/.local/bin/fd