#!/usr/bin/env/ bash 

sudo apt -y update
sudo apt -y install \
  zsh
hash -r
sudo chsh -s $(which zsh)
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended