[general]
live_config_reload = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 17.0

[window]
opacity = 0.9
startup_mode = "Maximized"
title = "terminal"
dynamic_padding = false
decorations = "None"

[terminal]
shell = "/home/pablokitz/dev/dotfiles/.config/alacritty/tmux-session-launch.sh"

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]